### PR TITLE
Fadeev/v1.0.162

### PR DESCRIPTION
**Pull request by fadeev**
- [x] Link styles use accent color defined in a CSS variable
- [x] "Found a issue?" banner

Screenshot 2020-04-16 at 19 40 00

- [x] Replaced Riot with Discord
- [x] Update VuePress and dependencies to the latest version

Closes https://github.com/allinbits/design/issues/252

### CODE REVIEW

**Comment by fadeev** [comment]
This is ready for review @lovincyrus @nassdonald. Replaced SVG with UTF-8 arrows, can't change color of visited links, because we're setting them with variables.

Just for reference what we can and can't do: https://developer.mozilla.org/en-US/docs/Web/CSS/:visited

@nassdonald let me know if we want to add interaction states to the banner, shadow, perhaps?

**Comment by nassdonald** [comment]
This is much better! Thanks for the updates. Cleans up the readability a lot and improves the theming support.

> What if made links primary color with gray thin underline, primary color with normal primary underline on hover, toggle opacity on active and black with gray underline on visited? Regular black text with thin underline brings less attention to visited links while still being recognizable as a link.

I like this suggestion. Let's do that. I've updated the link styles in [Figma DS](https://www.figma.com/file/7lITxBwOkiYCdeIzd9BTCq/Design-System-1.0?node-id=0%3A168). Remember to use `color: inherit;` rather than explicitly setting it to black - sorry if that was obvious. 😄 

> let me know if we want to add interaction states to the banner, shadow, perhaps?

Yeah let me document this in Figma for you…

**Comment by nassdonald** [comment]
We also need to update the support card to say:
> **Community chat**
> Chat with developers in the Cosmos Community chat.

Can we do that in this branch, for the sake of low-hanging fruit?
image

**Comment by fadeev** [comment]
That's in `.vuepress/config.js` in each repo.

**Comment by nassdonald** [comment]
Yes of course, sorry - moment of senility. 👴 

Could you 🙏 add that change to the PR when you update the SDK docs with these changes?

Once you've updated the link styling to reflect the discussion above, this is good to go! 💪

**Comment by fadeev** [comment]
Added interaction styles to the banner. Reverted back link styles, because page formatting is complicated enough without an additional style for `:visited`. We can get back to it for the next update.

**Pull request merged**
